const symbols=['🪙','💎','🧧','🪭','🍀','🐾','🌕','🧨'];
const scatter='🐯';
const reels=document.getElementById('reels');
const spinBtn=document.getElementById('spin');
const MIN_BET=1000,MAX_BET=100000,BET_STEP=5000;
const COIN_AD_REWARD=25000;
let balance=250000,bet=10000,spinning=false,lastWin=0;
let spinSpeed=1,autoMode=false,autoTimer=null; // .65 lambat, 1 normal, 1.45 cepat, 2 super
let musicOn=true,sfxOn=true,masterVolume=.55,audioCtx=null,musicTimer=null,scatterMusicTimer=null,scatterMusicIndex=0;
let freeSpins=0,freeWin=0,freeMode=false;
const fmt=n=>new Intl.NumberFormat('id-ID').format(Math.floor(n));
function save(){localStorage.setItem('jcr',JSON.stringify({balance,bet,musicOn,sfxOn,masterVolume,spinSpeed}))}
function load(){try{const d=JSON.parse(localStorage.getItem('jcr'));if(!d)return;balance=d.balance??balance;bet=Math.min(MAX_BET,Math.max(MIN_BET,d.bet??bet));musicOn=d.musicOn??musicOn;sfxOn=d.sfxOn??sfxOn;masterVolume=d.masterVolume??masterVolume;spinSpeed=d.spinSpeed??spinSpeed}catch(e){}}
function speedInfo(){if(spinSpeed===.65)return{icon:'🐢',name:'LAMBAT'};if(spinSpeed===1)return{icon:'▶',name:'NORMAL'};if(spinSpeed===1.45)return{icon:'⚡',name:'CEPAT 1×'};return{icon:'🚀',name:'SUPER 2×'}}
function render(){const c=document.getElementById('coins'),b=document.getElementById('bet'),bm=document.getElementById('betMobile'),w=document.getElementById('win'),wm=document.getElementById('winMobile'),sp=document.getElementById('speed'),sb=document.getElementById('superBtn'),so=document.getElementById('sound'),si=speedInfo();if(c)c.textContent=fmt(balance);if(b)b.textContent=fmt(bet);if(bm)bm.textContent=fmt(bet);if(w)w.textContent=fmt(lastWin);if(wm)wm.textContent=fmt(lastWin);if(sp)sp.innerHTML=si.icon+'<span>'+si.name+'</span>';if(sb)sb.classList.toggle('selectedSpeed',spinSpeed===2);if(so){so.innerHTML=musicOn?'🎵<small>MUSIK ON</small>':'🔇<small>MUSIK OFF</small>'}updateFreeBar()}
function updateFreeBar(){let el=document.getElementById('freeSpinBar');if(!el)return;if(freeMode)el.innerHTML=`🐯 FREE SPIN <b>${freeSpins}</b> • MENANG <b>${fmt(freeWin)}</b>`;else el.innerHTML='';el.classList.toggle('active',freeMode)}
function randomSymbol(){return symbols[Math.floor(Math.random()*symbols.length)]}
function makeGrid(){reels.innerHTML='';for(let c=0;c<5;c++){const reel=document.createElement('div');reel.className='reel';for(let r=0;r<3;r++){const cell=document.createElement('div');cell.className='symbol';cell.dataset.c=c;cell.dataset.r=r;cell.textContent=randomSymbol();reel.appendChild(cell)}reels.appendChild(reel)}}
function getAudio(){try{if(!audioCtx){const Ctx=window.AudioContext||window.webkitAudioContext;if(Ctx)audioCtx=new Ctx()}if(audioCtx&&audioCtx.state==='suspended')audioCtx.resume().catch(()=>{});return audioCtx}catch(e){return null}}
function beep(f=440,d=.08,type='sine',v=.08){if(!sfxOn)return;const ctx=getAudio();if(!ctx)return;try{const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,ctx.currentTime);g.gain.setValueAtTime(Math.max(.001,v*masterVolume),ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+d);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+d+.03)}catch(e){}}
function tigerLogoSound(){if(!sfxOn)return;const ctx=getAudio();if(!ctx)return;try{const o=ctx.createOscillator(),g=ctx.createGain(),l=ctx.createOscillator(),lg=ctx.createGain();o.type='sawtooth';o.frequency.setValueAtTime(180,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(72,ctx.currentTime+.42);g.gain.setValueAtTime(.001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.11*masterVolume,ctx.currentTime+.05);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.48);l.type='sine';l.frequency.setValueAtTime(48,ctx.currentTime);lg.gain.setValueAtTime(.06*masterVolume,ctx.currentTime);lg.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.5);o.connect(g);l.connect(lg);g.connect(ctx.destination);lg.connect(ctx.destination);o.start();l.start();o.stop(ctx.currentTime+.52);l.stop(ctx.currentTime+.52)}catch(e){}}
function sfx(n){if(!sfxOn)return;if(n==='logoTiger'){tigerLogoSound()}else if(n==='spin'){beep(220,.05,'triangle',.06);setTimeout(()=>beep(300,.05,'triangle',.05),45)}else if(n==='stop')beep(420,.07,'sine',.08);else if(n==='win'){beep(660,.1,'triangle',.1);setTimeout(()=>beep(880,.16,'triangle',.1),110)}else if(n==='scatter'){const notes=[196,247,294,392,523,659,784];notes.forEach((x,i)=>setTimeout(()=>beep(x,.18,i<2?'sine':'triangle',.12),i*95));setTimeout(()=>beep(98,.3,'sine',.16),80);setTimeout(()=>beep(147,.25,'sine',.13),260)}else if(n==='jackpot'){[523,659,784,1046,1318,1568].forEach((x,i)=>setTimeout(()=>beep(x,.18,'triangle',.13),i*105));setTimeout(()=>beep(82,.5,'sine',.18),0)}else if(n==='click')beep(520,.05,'triangle',.05)}
function musicNote(f,d=.18){if(!musicOn)return;const ctx=getAudio();if(!ctx)return;try{const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.018*masterVolume,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+d);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+d)}catch(e){}}
function startMusic(){if(!musicOn||musicTimer||freeMode)return;const melody=[220,277,330,294,247,294,370,330,196,247,294,330];let i=0;function loop(){if(!musicOn||freeMode){musicTimer=null;return}const n=melody[i%melody.length];musicNote(n,.38);if(i%4===0){setTimeout(()=>musicNote(n/2,.22),70)}if(i%3===1){setTimeout(()=>musicNote(n*1.25,.16),130)}i++;musicTimer=setTimeout(loop,520)}loop()}
function stopMusic(){if(musicTimer){clearTimeout(musicTimer);musicTimer=null}}
function unlockSound(){getAudio();if(musicOn&&!freeMode)startMusic()}
function scatterMusicBurst(){if(!musicOn)return;const seq=[147,196,247,294,392,494,588,784];seq.forEach((f,i)=>setTimeout(()=>musicNote(f,.22),i*105))}
function startScatterMusic(){stopScatterMusic();if(!musicOn)return;const beat=[147,196,247,294,392,294,247,196,392,494,588,494];function loop(){if(!freeMode||!musicOn){scatterMusicTimer=null;return}musicNote(beat[scatterMusicIndex++%beat.length],.2);scatterMusicTimer=setTimeout(loop,260)}loop()}
function stopScatterMusic(){if(scatterMusicTimer){clearTimeout(scatterMusicTimer);scatterMusicTimer=null}scatterMusicIndex=0}
function modal(title,html){document.getElementById('modalTitle').textContent=title;document.getElementById('modalBody').innerHTML=html;document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
document.getElementById('close').onclick=closeModal;
function countScatter(cells){return cells.filter(c=>c.textContent===scatter)}
function triggerFreeSpins(sc){freeMode=true;freeSpins=5;freeWin=0;stopAuto();sc.forEach(c=>c.classList.add('scatterWin'));sfx('scatter');scatterMusicBurst();startScatterMusic();updateFreeBar();modal('🐯 SCATTER TIGER!',`<div class="scatterTitle">🐯 3+ TIGER!</div><p>Scatter Tiger membuka <b>5 FREE SPIN</b>.</p><p>Musik Scatter aktif! Setiap free spin berjalan tanpa mengurangi saldo.</p><button id="startFree">🔥 MULAI FREE SPIN</button>`);setTimeout(()=>{const b=document.getElementById('startFree');if(b)b.onclick=()=>{closeModal();runFreeSpin()}},0)}
function runFreeSpin(){if(!freeMode||freeSpins<=0){finishFreeSpins();return}spin(true)}
function finishFreeSpins(){if(!freeMode)return;const amount=freeWin;freeMode=false;stopScatterMusic();freeSpins=0;updateFreeBar();if(amount<=0){modal('🐯 FREE SPIN SELESAI','<p>Belum ada kemenangan. Coba spin biasa lagi!</p>');return}modal('🎉 FREE SPIN SELESAI',`<div class="jackpot">${fmt(amount)} COIN</div><p>Tonton iklan demo untuk membuka hadiah kemenangan free spin.</p><button id="claimFree">📺 TONTON IKLAN & CLAIM</button>`);setTimeout(()=>{const b=document.getElementById('claimFree');if(b)b.onclick=()=>claimFreeReward(amount)},0)}
async function claimFreeReward(amount){closeModal();try{const ok=await window.showRewardedAd();if(ok===false){modal('Iklan Belum Selesai','<p>Hadiah belum diklaim karena iklan belum selesai.</p>');return}balance+=amount;lastWin=amount;save();render();sfx('win');modal('🎁 HADIAH FREE SPIN',`<div class="jackpot">+${fmt(amount)} COIN</div><p>Hadiah sudah masuk ke saldo game.</p>`)}catch(e){modal('Iklan Belum Tersedia','<p>Coba lagi beberapa saat.</p>')}}
function wildJackpotAnimation(cells){const targets=cells.filter((_,i)=>i%4===0).slice(0,5);targets.forEach((c,i)=>{c.classList.remove('win');c.classList.add('wildJackpot');c.textContent='🐯';setTimeout(()=>{c.classList.add('wildJackpotBig')},i*120)});sfx('jackpot');setTimeout(()=>{const old=document.getElementById('wildJackpotOverlay');if(old)old.remove();const o=document.createElement('div');o.id='wildJackpotOverlay';o.innerHTML='<div class="wildJackpotOverlayInner"><div class="wildTiger">🐯</div><div class="wildLabel">WILD JACKPOT!</div><div class="wildSub">JUNGLE TIGER x30</div></div>';document.body.appendChild(o);setTimeout(()=>o.classList.add('show'),20);setTimeout(()=>o.remove(),1900)},480);setTimeout(()=>targets.forEach(c=>{c.classList.remove('wildJackpot','wildJackpotBig')}),2200)}
function spin(isFree=false){if(spinning)return;if(!isFree&&!freeMode&&balance<bet){stopAuto();showOutOfCoins();return}unlockSound();spinning=true;spinBtn.disabled=true;if(!isFree)balance-=bet;lastWin=0;render();const arr=[...document.querySelectorAll('.reel')];if(!arr.length){makeGrid();spinning=false;spinBtn.disabled=false;return spin(isFree)}const interval=Math.round(115/spinSpeed),rounds=spinSpeed<=1?13:spinSpeed===1.45?10:8;arr.forEach((reel,col)=>{reel.classList.add('spinning');let ticks=0;const cells=[...reel.querySelectorAll('.symbol')];const stopAfter=rounds+col*3;const timer=setInterval(()=>{cells.forEach(cell=>{let useScatter=Math.random()<.035;cell.textContent=useScatter?scatter:randomSymbol()});if(ticks%4===0)sfx('spin');ticks++;if(ticks>=stopAfter){clearInterval(timer);reel.classList.remove('spinning');reel.classList.add('stopped');sfx('stop');setTimeout(()=>reel.classList.remove('stopped'),220);if(col===arr.length-1)setTimeout(()=>finish(isFree),250)}},interval)})}
function finish(isFree){const cells=[...document.querySelectorAll('.symbol')];const sc=countScatter(cells);if(sc.length>=3&&!isFree){triggerFreeSpins(sc);save();render();spinning=false;spinBtn.disabled=false;return}if(isFree&&sc.length>=3){freeSpins+=2;sfx('scatter');scatterMusicBurst();sc.forEach(c=>c.classList.add('scatterWin'));setTimeout(()=>sc.forEach(c=>c.classList.remove('scatterWin')),900)}let best=0,winning=[];for(let r=0;r<3;r++){const row=cells.filter(c=>+c.dataset.r===r);const counts={};row.forEach(c=>{if(c.textContent!==scatter)counts[c.textContent]=(counts[c.textContent]||0)+1});const max=Object.keys(counts).length?Math.max(...Object.values(counts)):0;if(max>=3){const sym=Object.keys(counts).find(k=>counts[k]===max);const mult=max===5?12:max===4?5:2;const win=bet*mult;if(win>best){best=win;winning=row.filter(c=>c.textContent===sym)}}}const jackpot=Math.random()<.018&&!isFree;if(jackpot){stopAuto();best=bet*30;winning=cells.filter((_,i)=>i%4===0).slice(0,5);wildJackpotAnimation(cells);modal('🐯 WILD JACKPOT!',`<div class="jackpot">JUNGLE JACKPOT!</div><p>🐯 WILD TIGER muncul dan mengalikan hadiah menjadi <b>${fmt(best)} COIN</b>.</p><p class="wildHint">WILD JACKPOT x30 BET</p><button id="claim">🎁 CLAIM HADIAH</button>`);setTimeout(()=>{const b=document.getElementById('claim');if(b)b.onclick=()=>claimJackpot(best)},0)}else if(best>0){if(isFree)freeWin+=best;else{lastWin=best;balance+=best}winning.forEach(c=>c.classList.add('win'));sfx('win');setTimeout(()=>winning.forEach(c=>c.classList.remove('win')),900)}save();render();spinning=false;spinBtn.disabled=false;if(isFree){freeSpins--;updateFreeBar();if(freeSpins>0)setTimeout(()=>runFreeSpin(),Math.round(850/spinSpeed));else setTimeout(()=>finishFreeSpins(),450)}else if(autoMode)autoTimer=setTimeout(()=>{if(autoMode&&!spinning)spin()},Math.round(1100/spinSpeed))}
async function claimJackpot(amount){closeModal();try{const ok=await window.showRewardedAd();if(ok===false){modal('Iklan Belum Selesai','<p>Hadiah diberikan setelah iklan selesai.</p>');return}giveReward(amount)}catch(e){showAdSimulation(amount,'JACKPOT')}}
function showAdSimulation(amount,label){modal('📺 IKLAN HADIAH',`<p>${label}</p><div class="count" id="count">5</div><p>Menunggu hadiah...</p>`);let s=5;const t=setInterval(()=>{s--;const c=document.getElementById('count');if(c)c.textContent=s;if(s<=0){clearInterval(t);closeModal();giveReward(amount)}},1000)}
function giveReward(amount){balance+=amount;lastWin=amount;save();render();modal('🎉 HADIAH DIKLAIM',`<div class="jackpot">+${fmt(amount)} COIN</div><p>Hadiah sudah masuk ke saldo game.</p>`);sfx('win')}
function showRewarded(amount,label){if(typeof window.showRewardedAd==='function'){Promise.resolve(window.showRewardedAd()).then(r=>{if(r!==false)giveReward(amount)}).catch(()=>modal('Iklan Belum Tersedia','<p>Coba lagi nanti.</p>'));return}showAdSimulation(amount,label)}
function showOutOfCoins(){stopAuto();modal('🪙 COIN HABIS','<p>Coin kamu habis.</p><button id="rewardCoins">🎁 BONUS +25.000 COIN</button><button id="cancelReward">⬅️ KEMBALI</button>');setTimeout(()=>{document.getElementById('cancelReward').onclick=closeModal;document.getElementById('rewardCoins').onclick=()=>{closeModal();showRewarded(COIN_AD_REWARD,'BONUS COIN')}},0)}
function openCoinReward(){unlockSound();modal('🪙 TAMBAH COIN',`<div class="jackpot">+${fmt(COIN_AD_REWARD)} COIN</div><p>Tonton iklan berhadiah sampai selesai untuk mendapatkan bonus coin.</p><button id="watchCoinAd">📺 TONTON IKLAN & DAPAT COIN</button><p style="font-size:11px;color:#9db0c9">Iklan hanya memberi bonus setelah selesai.</p>`);setTimeout(()=>{const b=document.getElementById('watchCoinAd');if(b)b.onclick=()=>{closeModal();showRewarded(COIN_AD_REWARD,'TAMBAH COIN')}},0)}
document.getElementById('addCoins').onclick=openCoinReward;
document.getElementById('bonus').onclick=()=>{unlockSound();const key='jcrBonusDay',today=new Date().toDateString();if(localStorage.getItem(key)===today){modal('🎁 Bonus Harian','<p>Bonus hari ini sudah diambil. Kembali lagi besok!</p>');return}balance+=10000;localStorage.setItem(key,today);save();render();modal('🎁 BONUS HARIAN',`<div class="jackpot">+10.000 COIN</div><p>Bonus sudah masuk!</p><button id="doubleBonus">🎁 BONUS TAMBAHAN</button>`);setTimeout(()=>{const b=document.getElementById('doubleBonus');if(b)b.onclick=()=>{closeModal();showRewarded(10000,'BONUS TAMBAHAN')}},0)};
function changeBet(dir){unlockSound();bet=dir<0?Math.max(MIN_BET,bet-BET_STEP):Math.min(MAX_BET,bet+BET_STEP);sfx('click');render();save()}
document.getElementById('minus').onclick=()=>changeBet(-1);document.getElementById('plus').onclick=()=>changeBet(1);
const mm=document.getElementById('minusMobile'),pm=document.getElementById('plusMobile');if(mm)mm.onclick=()=>changeBet(-1);if(pm)pm.onclick=()=>changeBet(1);
document.getElementById('speed').onclick=()=>{unlockSound();if(spinning)return;spinSpeed=spinSpeed===.65?1:spinSpeed===1?1.45:spinSpeed===1.45?.65:1;sfx('click');render();save()};
document.getElementById('superBtn').onclick=()=>{unlockSound();if(spinning)return;spinSpeed=spinSpeed===2?1:2;sfx('click');render();save()};
function stopAuto(){autoMode=false;if(autoTimer){clearTimeout(autoTimer);autoTimer=null}const b=document.getElementById('auto');if(b){b.innerHTML='▶ AUTO<br>OFF';b.classList.remove('activeAuto')}}
document.getElementById('auto').onclick=()=>{unlockSound();if(freeMode)return;autoMode=!autoMode;const b=document.getElementById('auto');b.innerHTML=autoMode?'⏹ AUTO<br>ON':'▶ AUTO<br>OFF';b.classList.toggle('activeAuto',autoMode);sfx('click');if(autoMode&&!spinning)spin()};spinBtn.onclick=()=>{unlockSound();sfx('click');if(freeMode)return;spin()};
document.getElementById('how').onclick=()=>modal('❓ CARA MAIN','<p>Tekan SPIN untuk memutar 5 reel.</p><p><b>🐯 Scatter Tiger:</b> dapatkan 3 atau lebih kepala Tiger di mana saja untuk membuka 5 Free Spin. Scatter tambahan saat Free Spin memberi +2 putaran.</p><p><b>🐯 WILD JACKPOT:</b> peluang jackpot memunculkan animasi Wild Tiger dan hadiah x30 bet.</p><p>3 simbol sama = 2× bet, 4 = 5×, 5 = 12×.</p><p>Bet: minimal 1.000 • maksimal 100.000 coin.</p>');
document.getElementById('sound').onclick=()=>{unlockSound();musicOn=!musicOn;if(musicOn){if(freeMode)startScatterMusic();else startMusic();sfx('click')}else{stopMusic();stopScatterMusic()}render();save()};
document.getElementById('settings').onclick=()=>{modal('⚙️ PENGATURAN',`<p>Atur suara game.</p><p>Bet saat ini: <b>${fmt(bet)}</b><br>Min ${fmt(MIN_BET)} • Max ${fmt(MAX_BET)}</p><button id="musicToggle">🎵 Musik: ${musicOn?'ON':'OFF'}</button><button id="sfxToggle">🔊 Efek: ${sfxOn?'ON':'OFF'}</button><p>Volume</p><input id="volumeSlider" type="range" min="0" max="100" value="${Math.round(masterVolume*100)}" style="width:100%"><p id="volumeValue">${Math.round(masterVolume*100)}%</p>`);setTimeout(()=>{const m=document.getElementById('musicToggle'),s=document.getElementById('sfxToggle'),sl=document.getElementById('volumeSlider'),v=document.getElementById('volumeValue');m.onclick=()=>{musicOn=!musicOn;if(musicOn){unlockSound();if(freeMode)startScatterMusic();startMusic()}else{stopMusic();stopScatterMusic();}m.innerHTML=`🎵 Musik: ${musicOn?'ON':'OFF'}`;save()};s.onclick=()=>{sfxOn=!sfxOn;s.innerHTML=`🔊 Efek: ${sfxOn?'ON':'OFF'}`;save()};sl.oninput=()=>{masterVolume=+sl.value/100;v.textContent=`${sl.value}%`;save()}},0)};
load();if(![.65,1,1.45,2].includes(spinSpeed))spinSpeed=1;makeGrid();render();let logoTigerPlayed=false;function unlockLogoTiger(){unlockSound();if(!logoTigerPlayed){logoTigerPlayed=true;sfx('logoTiger')}}document.addEventListener('pointerdown',unlockLogoTiger,{once:true});document.querySelectorAll('.tigerTap').forEach(el=>el.addEventListener('click',()=>{unlockSound();sfx('logoTiger')}));
